[package]
name = "webscraper"
version = "0.1.0"
authors = ["Nunes Nelson <nunes.nelson4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
